---
# handlers file for supervisor
- name: reload supervisor
  command: supervisorctl reload

- name: "supervisorctl restart {{ lookup('ini', 'app_name section=tenant file=variables.cnf') }}"
  command: "supervisorctl restart {{ lookup('ini', 'app_name section=tenant file=variables.cnf') }}"
