---
# tasks file for base_dependencies
- name: disable requiretty in sudo
  lineinfile:
    dest: /etc/sudoers
    line: "Defaults requiretty"
    state: absent
  become: yes
  become_user: root
  vars:
    ansible_ssh_pipelining: no
    
- name: Update Cache & Full System Update
  become: yes
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true

- name: Install Packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
