---
# tasks file for droplet
- name: "add public ssh key to digitalocean account"
  digital_ocean_sshkey:
    name: "{{app_name}}"
    oauth_token: "{{ do_token }}"
    ssh_pub_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
  register: sshkey_result

