"""empty message

Revision ID: 103fc855a10a
Revises: f4bd95e435a6
Create Date: 2021-10-06 09:33:03.107556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103fc855a10a'
down_revision = 'f4bd95e435a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_country_code'), ['country_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_country_code'))
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###
