"""empty message

Revision ID: 188ad55b8058
Revises: 4685eeb7c550
Create Date: 2022-01-21 15:00:34.946151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188ad55b8058'
down_revision = '4685eeb7c550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=128), nullable=True),
    sa.Column('lname', sa.String(length=128), nullable=True),
    sa.Column('orgname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('utm_source', sa.String(length=128), nullable=True),
    sa.Column('utm_medium', sa.String(length=128), nullable=True),
    sa.Column('utm_campaign', sa.String(length=128), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead'))
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_details'), ['details'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_orgname'), ['orgname'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_utm_campaign'), ['utm_campaign'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_utm_medium'), ['utm_medium'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_utm_source'), ['utm_source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_utm_source'))
        batch_op.drop_index(batch_op.f('ix_lead_utm_medium'))
        batch_op.drop_index(batch_op.f('ix_lead_utm_campaign'))
        batch_op.drop_index(batch_op.f('ix_lead_orgname'))
        batch_op.drop_index(batch_op.f('ix_lead_lname'))
        batch_op.drop_index(batch_op.f('ix_lead_fname'))
        batch_op.drop_index(batch_op.f('ix_lead_email'))
        batch_op.drop_index(batch_op.f('ix_lead_details'))

    op.drop_table('lead')
    # ### end Alembic commands ###
