"""empty message

Revision ID: 1c4562a99477
Revises: 903f39b48d8d
Create Date: 2021-09-14 20:21:23.270609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4562a99477'
down_revision = '903f39b48d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('auto_install')
        batch_op.drop_column('state')
        batch_op.drop_column('enable')
        batch_op.drop_column('installed_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installed_version', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('enable', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('auto_install', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
