"""empty message

Revision ID: 32c84e75129f
Revises: 8ad3a2ee4078
Create Date: 2022-01-20 10:44:39.879407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c84e75129f'
down_revision = '8ad3a2ee4078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_category_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
