"""empty message

Revision ID: 472ead25b013
Revises: 81ad56f2b820
Create Date: 2022-02-16 15:03:46.479234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472ead25b013'
down_revision = '81ad56f2b820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ModuleModels',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_ModuleModels_model_id_model')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_ModuleModels_module_id_module')),
    sa.PrimaryKeyConstraint('module_id', 'model_id', name=op.f('pk_ModuleModels'))
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_model_module_id_module'), 'module', ['module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_model_module_id_module'), type_='foreignkey')
        batch_op.drop_column('module_id')

    op.drop_table('ModuleModels')
    # ### end Alembic commands ###
