"""empty message

Revision ID: 8bc77b830acd
Revises: 897ca95f568e
Create Date: 2022-01-03 13:12:39.004910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc77b830acd'
down_revision = '897ca95f568e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_modules',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_modules_company_id_company')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_company_modules_module_id_module')),
    sa.PrimaryKeyConstraint('company_id', 'module_id', name=op.f('pk_company_modules'))
    )
    op.drop_table('CompanyModules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CompanyModules',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='fk_CompanyModules_company_id_company'),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name='fk_CompanyModules_module_id_module'),
    sa.PrimaryKeyConstraint('company_id', 'module_id', name='pk_CompanyModules')
    )
    op.drop_table('company_modules')
    # ### end Alembic commands ###
