"""empty message

Revision ID: 939105b4b91a
Revises: a487bde243b8
Create Date: 2022-01-13 08:54:35.770149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939105b4b91a'
down_revision = 'a487bde243b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_category', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_category'], ['feature_category.id'], name=op.f('fk_module_feature_feature_category_feature_category')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('fk_module_feature_module_id_module')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_feature'))
    )
    with op.batch_alter_table('module_feature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_feature_name'), ['name'], unique=False)

    with op.batch_alter_table('module_features', schema=None) as batch_op:
        batch_op.drop_index('ix_module_features_name')

    op.drop_table('module_features')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_features',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['feature_category.id'], name='fk_module_features_category_id_feature_category'),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name='fk_module_features_module_id_module'),
    sa.PrimaryKeyConstraint('id', name='pk_module_features')
    )
    with op.batch_alter_table('module_features', schema=None) as batch_op:
        batch_op.create_index('ix_module_features_name', ['name'], unique=False)

    with op.batch_alter_table('module_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_feature_name'))

    op.drop_table('module_feature')
    # ### end Alembic commands ###
