"""empty message

Revision ID: a487bde243b8
Revises: a89287a7cff8
Create Date: 2022-01-12 23:45:58.323832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a487bde243b8'
down_revision = 'a89287a7cff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_module_features_module_id_module'), 'module', ['module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_features', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_module_features_module_id_module'), type_='foreignkey')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
