"""empty message

Revision ID: a89287a7cff8
Revises: 8bc77b830acd
Create Date: 2022-01-12 23:44:29.489952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89287a7cff8'
down_revision = '8bc77b830acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_category'))
    )
    with op.batch_alter_table('feature_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_category_title'), ['title'], unique=False)

    op.create_table('module_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['feature_category.id'], name=op.f('fk_module_features_category_id_feature_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_features'))
    )
    with op.batch_alter_table('module_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_features_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_features_name'))

    op.drop_table('module_features')
    with op.batch_alter_table('feature_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_category_title'))

    op.drop_table('feature_category')
    # ### end Alembic commands ###
