"""empty message

Revision ID: dc504a974ca8
Revises: 
Create Date: 2021-08-09 22:54:16.461849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc504a974ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['module_category.id'], name=op.f('fk_module_category_parent_id_module_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module_category'))
    )
    with op.batch_alter_table('module_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_category_sequence'), ['sequence'], unique=False)

    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('shortdesc', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=60), nullable=True),
    sa.Column('maintainer', sa.String(length=60), nullable=True),
    sa.Column('contributors', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('installed_version', sa.String(length=60), nullable=True),
    sa.Column('latest_version', sa.String(length=60), nullable=True),
    sa.Column('published_version', sa.String(length=60), nullable=True),
    sa.Column('url', sa.String(length=60), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('auto_install', sa.Boolean(), nullable=True),
    sa.Column('state', sa.Enum('uninstallable', 'uninstalled', 'installed', 'to_upgrade', 'to_remove', 'to_install', name='stateenum'), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=True),
    sa.Column('menus_by_module', sa.Text(), nullable=True),
    sa.Column('reports_by_module', sa.Text(), nullable=True),
    sa.Column('views_by_module', sa.Text(), nullable=True),
    sa.Column('application', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('icon_image', sa.String(length=120), nullable=True),
    sa.Column('to_buy', sa.Boolean(), nullable=True),
    sa.Column('has_iap', sa.Boolean(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('web', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['module_category.id'], name=op.f('fk_module_category_id_module_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_module'))
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_state'))
        batch_op.drop_index(batch_op.f('ix_module_name'))

    op.drop_table('module')
    with op.batch_alter_table('module_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_category_sequence'))

    op.drop_table('module_category')
    # ### end Alembic commands ###
