"""empty message

Revision ID: f4bd95e435a6
Revises: 447695bb7bbc
Create Date: 2021-10-06 08:41:37.947091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bd95e435a6'
down_revision = '447695bb7bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_visitor_log_timezone'), ['timezone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_log_timezone'))
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
